Fix "make check" with --enable-relocatable.
When --enable-relocatable was passed to "configure", "make check" failed
while building datasheet-test:

	tests/data/datasheet-test.c: In function 'main':
	tests/data/datasheet-test.c:880: error: 'INSTALLDIR' undeclared (first use in this function)

Line 880 of that file is:

	set_program_name (argv[0]);

which is a little mysterious until one realizes that --enable-relocatable
defines set_program_name() as a macro that expands to a value that includes
INSTALLDIR.

So this commit fixes the problem by making sure that INSTALLDIR is defined
as part of CPPFLAGS for all compiles.