spreadlevel-plot: Fix missing #include <stdlib.h>
Reported by GCC:

spreadlevel-plot.c: In function ‘spreadlevel_plot_chart_destroy’:
spreadlevel-plot.c:84: error: implicit declaration of function
‘free’
preadlevel-plot.c:84: error: incompatible implicit declaration of
built-in function ‘free’